// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMChn3WOH7enPqnbVWCcmnxH4WfCIxZCc',
    appId: '1:51131796596:web:5a56ce433c79d1e9661521',
    messagingSenderId: '51131796596',
    projectId: 'test-flutter-app-bc72f',
    authDomain: 'test-flutter-app-bc72f.firebaseapp.com',
    storageBucket: 'test-flutter-app-bc72f.appspot.com',
    measurementId: 'G-CY0K40SKPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0POEFQpPzufM-ayZfHYHeVNNreJErYJY',
    appId: '1:51131796596:android:b0323fb196c5a6a4661521',
    messagingSenderId: '51131796596',
    projectId: 'test-flutter-app-bc72f',
    storageBucket: 'test-flutter-app-bc72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSFdMi3bN5Fk4IU9P3Nk-44_9jCTjVyHg',
    appId: '1:51131796596:ios:d49f2c99e1bac3b7661521',
    messagingSenderId: '51131796596',
    projectId: 'test-flutter-app-bc72f',
    storageBucket: 'test-flutter-app-bc72f.appspot.com',
    iosBundleId: 'com.exampledomain.authFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSFdMi3bN5Fk4IU9P3Nk-44_9jCTjVyHg',
    appId: '1:51131796596:ios:d49f2c99e1bac3b7661521',
    messagingSenderId: '51131796596',
    projectId: 'test-flutter-app-bc72f',
    storageBucket: 'test-flutter-app-bc72f.appspot.com',
    iosBundleId: 'com.exampledomain.authFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMChn3WOH7enPqnbVWCcmnxH4WfCIxZCc',
    appId: '1:51131796596:web:ddaf477e0f3fb573661521',
    messagingSenderId: '51131796596',
    projectId: 'test-flutter-app-bc72f',
    authDomain: 'test-flutter-app-bc72f.firebaseapp.com',
    storageBucket: 'test-flutter-app-bc72f.appspot.com',
    measurementId: 'G-PTZ0YD8MZS',
  );
}
